[target.x86_64-unknown-linux-gnu]
rustflags = [
  # "-C", "link-arg=-fuse-ld=mold",
  "-C", "link-arg=-fuse-ld=lld",
]

[unstable]
codegen-backend = true

[profile.dev]
opt-level = 3
codegen-backend = "cranelift"

[profile.dev.package."*"]
opt-level = 3
codegen-backend = "llvm"
